// Actions
export const API_DRIVERS_RESPONSE_SUCCESS = "API_DRIVERS_RESPONSE_SUCCESS";
export const API_DRIVERS_RESPONSE_ERROR = "API_DRIVERS_RESPONSE_ERROR";
export const GET_DRIVERS_TABLE_DATA = "GET_DRIVERS_TABLE_DATA";