// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_COMMISSIONS_CHARTS_DATA = "GET_COMMISSIONS_CHARTS_DATA";
export const GET_COMMISSIONS_TABLE_DATA = "GET_DIALTYPE_CHARTS_DATA"
export const GET_WIDGET_DATA = "GET_WIDGET_DATA";