// Actions
export const API_COMMISSIONS_RESPONSE_SUCCESS = "API_COMMISSIONS_RESPONSE_SUCCESS";
export const API_COMMISSIONS_RESPONSE_ERROR = "API_COMMISSIONS_RESPONSE_ERROR";
export const GET_COMMISSIONS_DATA = "GET_COMMISSIONS_DATA";