// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_TRANSATION_LIST = "GET_TRANSATION_LIST";
export const GET_WALLET_TRANSCTIONS = "GET_WALLET_TRANSCTIONS";
export const GET_ORDRER_LIST = "GET_ORDRER_LIST";
export const GET_WALLET = "GET_WALLET";
export const CREATE_WALLET = "CREATE_WALLET";
export const CREATE_WALLET_RESPONSE_SUCCESS = "CREATE_WALLET_RESPONSE_SUCCESS";
export const CREATE_WALLET_RESPONSE_ERROR = "CREATE_WALLET_RESPONSE_ERROR";