// Actions
export const API_BUSINESSES_RESPONSE_SUCCESS = "API_BUSINESSES_RESPONSE_SUCCESS";
export const API_BUSINESSES_RESPONSE_ERROR = "API_BUSINESSES_RESPONSE_ERROR";
export const GET_BUSINESSES_TABLE_DATA = "GET_BUSINESSES_TABLE_DATA";