// Actions
export const API_USERS_RESPONSE_SUCCESS = "API_USERS_RESPONSE_SUCCESS";
export const API_USERS_RESPONSE_ERROR = "API_USERS_RESPONSE_ERROR";
export const GET_USERS_TABLE_DATA = "GET_USERS_TABLE_DATA";